### ISSUE TITLE
Emitting something wrong for annotations

### ISSUE THREAD

**Issue by alexeagle** [angular/ts2dart#56] opened 2015-03-20 00:01 UTC
I am surprised we can even parse the annotations at present.

eg. line 1, column 1188 of dist/dart.ts2dart/injector_spec.dart

we generate
class CarWithInject { Engine engine ; CarWithInject ( [ Inject = ( TurboEngine ) ] , Engine engine ) { this . engine = engine ; } }

from
class CarWithInject {
  engine:Engine;
  constructor(@Inject(TurboEngine) engine:Engine) {
    this.engine = engine;
  }
}

**Comment by alexeagle** [comment] 2015-03-20 00:02
the error from dart_style is
Normal parameters must occur before optional parameters
not that it really matters since we are producing garbage

**Comment by mprobst** [comment] 2015-03-25 02:29
I cannot reproduce this. Maybe it got fixed by accident in our parameter handling changes?

**Closed by mprobst** 2015-03-25 02:29 UTC

**Comment by alexeagle** [comment] 2015-03-25 04:16
Probably it is fixed now that we parse the annotations.
