### ISSUE TITLE
Type information lost in named parameter list (part 2)

### ISSUE THREAD

**Issue by mhevery** [angular/ts2dart#361] opened 2016-04-04 18:30 UTC
Given: 
```
RouteDefinition {
  name: string;
}
class AbstractRoute {
  constructor({name}: RouteDefinition) {}
}
```

Expected: 
```
class AbstractRoute {
  AbstractRoute({String name}) {}
}
```

Was:
```
class AbstractRoute {
  AbstractRoute({name}) {}
}
```

**Comment by mhevery** [comment] 2016-04-04 18:49
Also fails in this case:
Given:
```
interface RegexSerializer { (params: {[key: string]: any}): GeneratedUrl; }
interface RouteDefinition {
  serializer?: RegexSerializer;
}
```

Expected:
```
typedef GeneratedUrl RegexSerializer(Map<String, dynamic> params);
abstract class RouteDefinition {
  final RegexSerializer serializer; // <<<<< Expected change
  const RouteDefinition({this.serializer});
}
```

Actual:
```
typedef GeneratedUrl RegexSerializer(Map<String, dynamic> params);
abstract class RouteDefinition {
  final Function serializer;
  const RouteDefinition({this.serializer});
}
```

**Comment by mprobst** [comment] 2016-04-04 20:29
The first example is tricky in the general case. You're asking to correlate
the left hand side property 'name' with the property definition of the same
name in the rhs type. I'll have to take a look at the available APIs.

The lost property type with the regexserializer is a separate issue.

Miško Hevery <notifications@github.com> schrieb am Mo., 4. Apr. 2016, 20:49:

**Comment by mhevery** [comment] 2016-04-07 23:18
Any update?

**Comment by mprobst** [comment] 2016-04-08 13:00
I cannot reproduce the `final Function serializer;` issue, see https://reviews.angular.io/D56.

Will take a look at the `RouteDefinition` destructuring next.

**Comment by mprobst** [comment] 2016-04-11 23:37
This should be fixed.

**Closed by mprobst** 2016-04-11 23:37 UTC
Labels: DDC_Blocking
